-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 19:38:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
USE `railway`;

-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorias` ;

CREATE TABLE IF NOT EXISTS `categorias` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `perfil` ENUM('cliente', 'admin') NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enderecos` ;

CREATE TABLE IF NOT EXISTS `enderecos` (
  `id_endereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `estado` CHAR(2) NOT NULL,
  `principal` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produtos` ;

CREATE TABLE IF NOT EXISTS `produtos` (
  CONSTRAINT chk_estoque CHECK (`estoque_atual` >= 0),
  `id_produto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_categoria` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  `preco_venda` DECIMAL(10,2) NOT NULL,
  `estoque_atual` INT UNSIGNED NOT NULL DEFAULT 0,
  `custo_unitario` DECIMAL(10,2) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `id_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cupons` ;

CREATE TABLE IF NOT EXISTS `cupons` (
  `id_cupom` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `tipo` ENUM('percentual', 'fixo') NOT NULL,
  `valor` DECIMAL(10,2) UNSIGNED NOT NULL,
  `quantidade_total` INT UNSIGNED NOT NULL,
  `quantidade_usada` INT UNSIGNED ZEROFILL NOT NULL,
  `validade` DATE NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_cupom`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedidos` ;

CREATE TABLE IF NOT EXISTS `pedidos` (
  `id_pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `status` ENUM('pendente', 'pago', 'enviado', 'entregue', 'cancelado') NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `id_endereco` INT UNSIGNED NOT NULL,
  `id_cupom` INT UNSIGNED NULL,
  `subtotal` DECIMAL(10,2) UNSIGNED NOT NULL,
  `desconto` DECIMAL(10,2) UNSIGNED ZEROFILL NOT NULL,
  `frete` DECIMAL(10,2) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_endereco_idx` (`id_endereco` ASC) VISIBLE,
  INDEX `id_cupom_idx` (`id_cupom` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_cupom`
    FOREIGN KEY (`id_cupom`)
    REFERENCES `cupons` (`id_cupom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itens_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itens_pedido` ;

CREATE TABLE IF NOT EXISTS `itens_pedido` (
  `id_item` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pedido` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  `desconto_aplicado` DECIMAL(10,2) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id_item`),
  INDEX `itens_pedido_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `id_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `id_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promocoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `promocoes` ;

CREATE TABLE IF NOT EXISTS `promocoes` (
  `id_promocao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_promocao` VARCHAR(45) NOT NULL,
  `percentual_desconto` DECIMAL(5,2) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id_promocao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promocao_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `promocao_produtos` ;

CREATE TABLE IF NOT EXISTS `promocao_produtos` (
  `id_relacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_promocao` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_relacao`),
  INDEX `id_promocao_idx` (`id_promocao` ASC) VISIBLE,
  INDEX `id_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `id_promocao`
    FOREIGN KEY (`id_promocao`)
    REFERENCES `promocoes` (`id_promocao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promocao_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formas_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formas_pagamento` ;

CREATE TABLE IF NOT EXISTS `formas_pagamento` (
  `id_forma` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_forma` VARCHAR(50) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_forma`),
  UNIQUE INDEX `nome_forma_UNIQUE` (`nome_forma` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transacoes_financeiras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transacoes_financeiras` ;

CREATE TABLE IF NOT EXISTS `transacoes_financeiras` (
  `id_transacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pedido` INT UNSIGNED NOT NULL,
  `id_forma` INT UNSIGNED NOT NULL,
  `valor_recebido` DECIMAL(10,2) NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `status_pagamento` ENUM('Pendente', 'Confirmado', 'Estornado', 'Recusado') NOT NULL,
  `codigo_externo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_transacao`),
  INDEX `id_pedido_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `id_forma_idx` (`id_forma` ASC) VISIBLE,
  CONSTRAINT `fk_transacoes_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_forma`
    FOREIGN KEY (`id_forma`)
    REFERENCES `formas_pagamento` (`id_forma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imagens_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imagens_produto` ;

CREATE TABLE IF NOT EXISTS `imagens_produto` (
  `id_imagem` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_produto` INT UNSIGNED NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `principal` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_imagem`),
  INDEX `id_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_imagens_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho` ;

CREATE TABLE IF NOT EXISTS `carrinho` (
  `id_item` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  `adicionado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_item`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinho_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliacoes` ;

CREATE TABLE IF NOT EXISTS `avaliacoes` (
  CONSTRAINT `chk_nota` CHECK (`nota` BETWEEN 1 AND 5),
  `id_avaliacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_produto` INT UNSIGNED NOT NULL,
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_pedido` INT UNSIGNED NOT NULL,
  `nota` TINYINT UNSIGNED NOT NULL,
  `comentario` TEXT NULL,
  `data_avaliacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_avaliacao`),
  INDEX `id_produto_idx` (`id_produto` ASC) VISIBLE,
  INDEX `Id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_pedido_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacoes_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacoes_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacoes_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `audit_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `audit_logs` ;

CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id_log` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `tabela_afetada` VARCHAR(100) NOT NULL,
  `acao` VARCHAR(20) NOT NULL,
  `dados_anteriores` TEXT NULL,
  `dados_novos` TEXT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_auditlogs_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
